apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-adapter
  template:
    metadata:
      labels:
        app: weather-adapter
    spec:
      containers:
        - name: weather-adapter
          image: us-central1-docker.pkg.dev/weatherapp-gke/weather-service-repo/weather-adapter:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-adapter-secret
                  key: WEATHER_API_KEY
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "812Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3