apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-adapter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-adapter
  template:
    metadata:
      labels:
        app: weather-adapter
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: weather-adapter
          image: ghcr.io/polikkox/weather-adapter:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3