apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-adapter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-adapter
  template:
    metadata:
      labels:
        app: weather-adapter
    spec:
      containers:
        - name: weather-adapter
          image: ghcr.io/polikkox/weather-adapter:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5